# Generated by Django 4.2.5 on 2023-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('product_seller', models.CharField(default='', max_length=200)),
                ('product_reviews', models.IntegerField(default='')),
                ('product_price', models.IntegerField(default='')),
            ],
        ),
    ]
