# Generated by Django 4.2.5 on 2023-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productcat_product_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcat',
            name='producT_cat_image',
            field=models.ImageField(default='', upload_to='cat/images/'),
        ),
    ]
