# Generated by Django 4.2.5 on 2023-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productcat_product_cat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('contact', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
