# Generated by Django 4.2.5 on 2023-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_assoc',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_assoc',
            field=models.ManyToManyField(to='ecommerce.product'),
        ),
    ]
