# Generated by Django 4.2.5 on 2023-10-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_cart_product_assoc_cart_product_assoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_assoc',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_assoc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
