# Generated by Django 4.2.5 on 2023-10-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
